### ISSUE TITLE
dispute functionality

### ISSUE THREAD

**Issue by themandalore** [tellor-io/layer#3]

**Comment by oraclown** [comment]
notes/ideas from call:
- disputing just reporter addresses specifically
- need some way to track whether some reporter was a part of a medianized value over the last 21 days (or some other time window)
- if yes, then we go back and flag each of those medians, so end users know 
- add in weighted stddev to medianized tx so user can omit data that has too high standard deviation
- dispute function just takes reporter address and report id (to flag an individual contribution of theirs
- dispute function that just takes reporter address to flag all of their contributions
- values are immediately flagged when dispute function is called
- maybe can add evidence to dispute (evidence module?) (maybe this costs money)
- individual reporters will need logic/rules to vote instantly / sign off on disputes. this comes down to just checking percentage difference thresholds between the disputed value and the voting reporters of submitted value or some calc involving the std deviation
- punishment severity maybe an argument to dispute function
- example: severity "warning" , dispute initiator must pay 1% of validator stake fee
- dispute(reporter, severity, value)
- half of dispute fee is burned, half given to voters to incentivize voting
-

**Comment by tkernell** [comment]
How can we flag bad data which has reached 2/3+ consensus, but for whatever accidental reason is inaccurate? We don't want users consuming it. Should there be some fee?
