### ISSUE TITLE
Add validator nonce to bridge

### ISSUE THREAD

**Issue by themandalore** [tellor-io/layer#42]
you sign (nonce, oracleData)

then when you verify an attestation, you input oracleData and it must match the nonce.  This is so that the validator set can't change and push a bad block to the system. 

You don't need this nonce for oracleData (like celestia) since we don't have a front running problem as oracle data is additive, not unique per block

**Comment by themandalore** [comment]
sign(oldNonce, newNonce, newValSetHash)

**Comment by brendaloya** [comment]
timestmap was implemented
