### ISSUE TITLE
Research -- Add seperate reporters vs validators

### ISSUE THREAD

**Issue by themandalore** [tellor-io/layer#57]
So validators can be reporters, but reporters can also be seperate.  

Same logic, but no min stake 

The reason -- we can keep the validator set low (for bridging purposes), but have the reporter threshold high.  You'd just run a node (not a validator) and submit txns in the right order.  Limiting it to the validator set is very restrictive on costs for new data points.  

The big research is "how many validators?"  Can we fit 1k reports in a block?  How about 10k?

**Comment by themandalore** [comment]
Another thing to think about is the balance between rewards?  Do I want to validate or report? whats the reward split?  Do I want to delegate or report if too small to validate?  

Do we need two tokens?  Or just some balancing mechanism?  Can you delegate and report?

**Comment by themandalore** [comment]
maybe dPoS for validators, PoS for reporters... this solves competing capital (you could delegate reporting power sepearately from validating power)

Say party A has 100 TRB.  You could delegate 100 to Validator Y and then 100 stake as a reporter

**Comment by brendaloya** [comment]
so far the reporter and validator set have been separated.
