### ISSUE TITLE
Add batching and queue for stake changes

### ISSUE THREAD

**Issue by themandalore** [tellor-io/layer#58]
We should only do withdraw/deposit stake (to validator set) once a day.  This makes it so that even in busy times, we don't have too many people depositing and forcing changes that need to be pushed across on the bridge side

Additionaly, create a queue.  The validator set should be able to change at most 10% per day (up or down).  It just makes a line if its more than that and you wait until the next day.

**Comment by themandalore** [comment]
change this to just limit to 5% change.  Then wait 12 hours.  Just for deposits/withdrawals

**Comment by themandalore** [comment]
need to limit tipping in someway..just lock for 12 hours?

**Comment by themandalore** [comment]
just lock for 12 hours, and then we also have the 2% fee.

**Comment by brendaloya** [comment]
Currently tips increase stake and can be a way to go around the max 5% change allowed. Tips are not issued free floating to avoid getting attacked to increase voting/validation power. Some options we are thinking about:

-adding a delay so the change would have an effect on their validation/voting power 12 hours later (only increase their stake 1% of the tip/12 hours?)
-or/and increase the 2% tip fee to be increase with tips
