### ISSUE TITLE
block processing

### ISSUE THREAD

**Issue by themandalore** [tellor-io/layer#6]
3 block method

1st block - tips get submitted
2nd block - submit value (commit). -- condense as much as we can (into 1 transaction if possible, but also condense across queryIds (multiple queryId batchSubmit)) -- proposer condenses

3rd block - submit value (reveal (each validator/reporter)  / median (done by proposer)

**Comment by themandalore** [comment]
prepareProposal / processProposal functionality

**Comment by brendaloya** [comment]
-Custom mempool lanes for allocating 80% of block for submit values and 20% everything else
